name: ChatGPT Bot

on:
  issue_comment:
    types:
      - created

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/chatgpt-bot@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: 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

# copy from https://github.com/marketplace/actions/chatgpt-assistant
